# Generated by Django 4.0.4 on 2022-05-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_user_id_table_user'),
        ('sents', '0003_alter_product_product_id_alter_table_producter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_back',
            old_name='users_domain_id',
            new_name='users_domain',
        ),
        migrations.AlterField(
            model_name='product',
            name='production_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sents.table'),
        ),
        migrations.AlterField(
            model_name='product_back',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.table'),
        ),
    ]
