# Generated by Django 4.0.4 on 2022-05-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sents', '0004_rename_product_id_product_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='production_id',
            new_name='production',
        ),
        migrations.RenameField(
            model_name='product_back',
            old_name='product_id',
            new_name='product',
        ),
    ]
