# Generated by Django 4.0.4 on 2022-05-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_id_telegram_ids_users_and_more'),
        ('sents', '0005_rename_production_id_product_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_back',
            name='users_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_domains'),
        ),
    ]
