# Generated by Django 4.0.4 on 2022-05-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sents', '0006_alter_product_back_users_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='producter_id',
            new_name='producter',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
