# Generated by Django 4.0.4 on 2022-05-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_table_initial_remove_table_loading_price_and_more'),
        ('users', '0004_rename_users_id_telegram_ids_users_and_more'),
        ('sents', '0007_rename_producter_id_table_producter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('initial', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.table')),
            ],
        ),
    ]
