# Generated by Django 4.0.4 on 2022-05-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_table_initial_remove_table_loading_price_and_more'),
        ('sents', '0011_remove_table_fuller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage+', to='product.table'),
        ),
    ]
