# Generated by Django 4.0.2 on 2022-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_values',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.BigIntegerField()),
                ('reason_add', models.CharField(max_length=255)),
                ('production_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('product_value', models.BigIntegerField()),
                ('product_price', models.BigIntegerField()),
                ('production_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productioner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('worker_id', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('production_id', models.BigIntegerField()),
                ('production_sanction', models.BooleanField(null=True)),
                ('production_sanction_date', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('fuller_id', models.BigIntegerField()),
                ('company_id', models.BigIntegerField(null=True)),
                ('sanctioner_id', models.BigIntegerField()),
                ('sanction', models.BooleanField(null=True)),
                ('sanction_date', models.CharField(max_length=255, null=True)),
                ('productioner_comment', models.CharField(max_length=255, null=True)),
                ('sanctioner_comment', models.CharField(max_length=255, null=True)),
                ('overall', models.BigIntegerField(null=True)),
            ],
        ),
    ]
