# Generated by Django 4.0.4 on 2022-05-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_user_id_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='table',
            name='loading_price',
        ),
        migrations.RemoveField(
            model_name='table',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='table',
            name='production_price',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
    ]
