# Generated by Django 4.0.2 on 2022-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('users_id', models.BigIntegerField()),
                ('business_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diliver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('users_id', models.BigIntegerField()),
                ('avto_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('sure_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tell_num', models.CharField(max_length=20)),
                ('type_work', models.CharField(max_length=20)),
                ('is_creator', models.BooleanField(null=True)),
                ('working_with', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_ids',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField()),
                ('users_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
    ]
