# Generated by Django 4.0.4 on 2022-04-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_ids',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.table'),
        ),
    ]
